-- Voyage Data Seed
-- Generated: 2026-04-20T11:50:06.216Z

CREATE TABLE IF NOT EXISTS transit_times (id INT AUTO_INCREMENT PRIMARY KEY, from_position VARCHAR(255), to_destination VARCHAR(255), days INT, UNIQUE KEY uq_route (from_position, to_destination));
INSERT INTO transit_times (from_position, to_destination, days) VALUES
('loads AG',NULL,undefined),
('Open AG',NULL,undefined),
('WCI',NULL,undefined),
('Galle',NULL,undefined),
('ECI',NULL,undefined),
('Bangladesh',NULL,undefined),
('Suez',NULL,undefined),
('Botany',NULL,undefined),
('Tanzania',NULL,undefined),
('loads Prince Rupert',NULL,undefined),
('Singapore ballast',NULL,undefined),
('Singapore laden',NULL,undefined),
('Cape laden',NULL,undefined),
('Port Louis laden',NULL,undefined),
('Malaysia ballast',NULL,undefined),
('Malaysia laden',NULL,undefined),
('Indo',NULL,undefined),
('Thailand',NULL,undefined),
('Vietnam',NULL,undefined),
('Philippines',NULL,undefined),
('Taiwan',NULL,undefined),
('Ningbo',NULL,undefined),
('East China',NULL,undefined),
('China',NULL,undefined),
('South China',NULL,undefined),
('Korea',NULL,undefined),
('Far East',NULL,undefined),
('Japan',NULL,undefined),
('North China',NULL,undefined),
('Australia',NULL,undefined),
('Turkey',NULL,undefined),
('WAF',NULL,undefined),
('Oman',NULL,undefined),
('Open USG',NULL,undefined),
('loads USG',NULL,undefined),
('loads MH',NULL,undefined),
('USG',NULL,undefined),
('Balboa',NULL,undefined),
('Far East',NULL,undefined),
('North China',NULL,undefined),
('Japan',NULL,undefined),
('Ningbo',NULL,undefined),
('East China',NULL,undefined),
('China',NULL,undefined),
('Jamaica',NULL,undefined),
('Korea',NULL,undefined),
('Taiwan',NULL,undefined),
('South China',NULL,undefined),
('Suez',NULL,undefined),
('Philippines',NULL,undefined),
('Indo',NULL,undefined),
('Vietnam',NULL,undefined),
('Australia',NULL,undefined),
('Turkey',NULL,undefined),
('Tanzania',NULL,undefined),
('Chile',NULL,undefined),
('Mexico',NULL,undefined),
('Malaysia laden',NULL,undefined),
('Malaysia ballast',NULL,undefined),
('Singapore ballast',NULL,undefined),
('Singapore laden',NULL,undefined),
('Port Louis laden',NULL,undefined),
('Thailand',NULL,undefined),
('Eu',NULL,undefined),
('Gibraltar',NULL,undefined),
('Caribs',NULL,undefined),
('Mohammedia',NULL,undefined),
('Dortyol',NULL,undefined),
('Quintero',NULL,undefined),
('Suape',NULL,undefined),
('Botany',NULL,undefined),
('Flushing',NULL,undefined),
('Santos',NULL,undefined),
('East Med',NULL,undefined),
('Ocoa Bay',NULL,undefined),
('Las Palmas (Canary Islands)',NULL,undefined),
('Monteverde',NULL,undefined),
('West Mexico',NULL,undefined),
('Honolulu',NULL,undefined),
('Manza (Mex)',NULL,undefined),
('loads USG',NULL,undefined),
('Open AG',NULL,undefined),
('Open USG',NULL,undefined),
('Singapore ballast',NULL,undefined),
('Singapore laden',NULL,undefined),
('Port Louis ballast',NULL,undefined),
('Port Louis laden',NULL,undefined),
('Cape ballast',NULL,undefined),
('Malaysia ballast',NULL,undefined),
('Malaysia laden',NULL,undefined),
('Bahamas',NULL,undefined),
('Mexico',NULL,undefined),
('Cayman',NULL,undefined),
('Jamaica',NULL,undefined),
('Korea',NULL,undefined),
('Caribs',NULL,undefined),
('Suez',NULL,undefined),
('Tanzania',NULL,undefined),
('Japan',NULL,undefined),
('North China',NULL,undefined),
('Galle',NULL,undefined),
('Far East',NULL,undefined),
('Richards Bay',NULL,undefined),
('Quintero',NULL,undefined),
('Suape',NULL,undefined),
('Santos',NULL,undefined),
('Mohammedia',NULL,undefined),
('Gibraltar',NULL,undefined),
('Bangladesh',NULL,undefined),
('loads Prince Rupert',NULL,undefined),
('Flushing',NULL,undefined),
('Dortyol',NULL,undefined),
('Eu',NULL,undefined),
('Algeria',NULL,undefined),
('Terneuzen',NULL,undefined),
('East Med',NULL,undefined),
('Turkey',NULL,undefined),
('Ocoa Bay',NULL,undefined),
('Ningbo',NULL,undefined),
('East China',NULL,undefined),
('Botany',NULL,undefined),
('China',NULL,undefined),
('South China',NULL,undefined),
('Indo',NULL,undefined),
('Taiwan',NULL,undefined),
('Thailand',NULL,undefined),
('Vietnam',NULL,undefined),
('Oman',NULL,undefined),
('Philippines',NULL,undefined),
('Australia',NULL,undefined),
('ECI',NULL,undefined),
('WCI',NULL,undefined),
('WAF',NULL,undefined),
('Galle',NULL,undefined),
('loads WAF',NULL,undefined),
('Botany',NULL,undefined),
('North China',NULL,undefined),
('Mexico',NULL,undefined),
('Open AG',NULL,undefined),
('Mohammedia',NULL,undefined),
('Gibraltar',NULL,undefined),
('Turkey',NULL,undefined),
('Singapore ballast',NULL,undefined),
('Singapore laden',NULL,undefined),
('Port Louis ballast',NULL,undefined),
('Port Louis laden',NULL,undefined),
('Malaysia ballast',NULL,undefined),
('Malaysia laden',NULL,undefined),
('Indo',NULL,undefined),
('Thailand',NULL,undefined),
('Cape ballast',NULL,undefined),
('Tanzania',NULL,undefined),
('Vietnam',NULL,undefined),
('Philippines',NULL,undefined),
('South China',NULL,undefined),
('Taiwan',NULL,undefined),
('Ningbo',NULL,undefined),
('East China',NULL,undefined),
('Richards Bay',NULL,undefined),
('Bangladesh',NULL,undefined),
('loads Prince Rupert',NULL,undefined),
('Oman',NULL,undefined),
('China',NULL,undefined),
('Korea',NULL,undefined),
('Far East',NULL,undefined),
('Japan',NULL,undefined),
('Australia',NULL,undefined),
('East Med',NULL,undefined),
('Eu',NULL,undefined),
('WCI',NULL,undefined),
('ECI',NULL,undefined),
('Suape',NULL,undefined),
('Santos',NULL,undefined),
('Suez',NULL,undefined),
('Caribs',NULL,undefined),
('Dortyol',NULL,undefined),
('Ocoa Bay',NULL,undefined),
('Quintero',NULL,undefined),
('MH',NULL,undefined),
('loads MH',NULL,undefined),
('loads USG',NULL,undefined),
('USG',NULL,undefined),
('Cape ballast',NULL,undefined),
('Port Louis ballast',NULL,undefined),
('Port Louis laden',NULL,undefined),
('Bahamas',NULL,undefined),
('Mexico',NULL,undefined),
('Cayman',NULL,undefined),
('Caribs',NULL,undefined),
('Quintero',NULL,undefined),
('Suape',NULL,undefined),
('Santos',NULL,undefined),
('Mohammedia',NULL,undefined),
('Gibraltar',NULL,undefined),
('Flushing',NULL,undefined),
('WAF',NULL,undefined),
('loads Bethioua',NULL,undefined),
('loads Prince Rupert',NULL,undefined),
('Richards Bay',NULL,undefined),
('Dortyol',NULL,undefined),
('Turkey',NULL,undefined),
('Eu',NULL,undefined),
('Algeria',NULL,undefined),
('Terneuzen',NULL,undefined),
('East Med',NULL,undefined),
('Tanzania',NULL,undefined),
('Singapore ballast',NULL,undefined),
('Singapore laden',NULL,undefined),
('Malaysia ballast',NULL,undefined),
('Malaysia laden',NULL,undefined),
('Indo',NULL,undefined),
('ECI',NULL,undefined),
('WCI',NULL,undefined),
('AG',NULL,undefined),
('Suez',NULL,undefined),
('Galle',NULL,undefined),
('Ocoa Bay',NULL,undefined),
('Ningbo',NULL,undefined),
('East China',NULL,undefined),
('South China',NULL,undefined),
('North China',NULL,undefined),
('Taiwan',NULL,undefined),
('Thailand',NULL,undefined),
('Vietnam',NULL,undefined),
('Philippines',NULL,undefined),
('Australia',NULL,undefined),
('Korea',NULL,undefined),
('Japan',NULL,undefined),
('Far East',NULL,undefined),
('Oman',NULL,undefined),
('Singapore laden',NULL,undefined),
('Singapore ballast',NULL,undefined),
('ECI',NULL,undefined),
('Botany',NULL,undefined),
('Port Louis laden',NULL,undefined),
('Cape laden',NULL,undefined),
('Cape ballast',NULL,undefined),
('Malaysia ballast',NULL,undefined),
('Malaysia laden',NULL,undefined),
('Indo',NULL,undefined),
('Thailand',NULL,undefined),
('Galle',NULL,undefined),
('Richards Bay',NULL,undefined),
('loads Prince Rupert',NULL,undefined),
('Vietnam',NULL,undefined),
('Philippines',NULL,undefined),
('Taiwan',NULL,undefined),
('Ningbo',NULL,undefined),
('East China',NULL,undefined),
('China',NULL,undefined),
('South China',NULL,undefined),
('Korea',NULL,undefined),
('Far East',NULL,undefined),
('Japan',NULL,undefined),
('North China',NULL,undefined),
('Australia',NULL,undefined),
('Tanzania',NULL,undefined),
('Singapore ballast',NULL,undefined),
('Singapore laden',NULL,undefined),
('Port Louis laden',NULL,undefined),
('Malaysia ballast',NULL,undefined),
('Malaysia laden',NULL,undefined),
('Indo',NULL,undefined),
('Thailand',NULL,undefined),
('Vietnam',NULL,undefined),
('Philippines',NULL,undefined),
('Taiwan',NULL,undefined),
('Ningbo',NULL,undefined),
('East China',NULL,undefined),
('China',NULL,undefined),
('South China',NULL,undefined),
('Korea',NULL,undefined),
('Far East',NULL,undefined),
('Japan',NULL,undefined),
('North China',NULL,undefined),
('Australia',NULL,undefined),
('Cape laden',NULL,undefined),
('Tanzania',NULL,undefined),
('Singapore ballast',NULL,undefined),
('Botany',NULL,undefined),
('Malaysia ballast',NULL,undefined),
('Malaysia laden',NULL,undefined),
('Singapore laden',NULL,undefined),
('loads AG',NULL,undefined),
('Indo',NULL,undefined),
('Cape laden',NULL,undefined),
('Port Louis laden',NULL,undefined),
('Thailand',NULL,undefined),
('Vietnam',NULL,undefined),
('Philippines',NULL,undefined),
('Taiwan',NULL,undefined),
('Ningbo',NULL,undefined),
('East China',NULL,undefined),
('China',NULL,undefined),
('South China',NULL,undefined),
('Korea',NULL,undefined),
('Far East',NULL,undefined),
('Japan',NULL,undefined),
('North China',NULL,undefined),
('Australia',NULL,undefined),
('Tanzania',NULL,undefined),
('Southwest China',NULL,undefined),
('South Korea',NULL,undefined),
('Philippines',NULL,undefined),
('Taiwan',NULL,undefined),
('East China',NULL,undefined),
('Ningbo',NULL,undefined),
('China',NULL,undefined),
('Korea',NULL,undefined),
('Far East',NULL,undefined),
('Japan',NULL,undefined),
('North China',NULL,undefined),
('Singapore ballast',NULL,undefined),
('Singapore laden',NULL,undefined),
('Botany',NULL,undefined),
('Malaysia ballast',NULL,undefined),
('Malaysia laden',NULL,undefined),
('Indo',NULL,undefined),
('Thailand',NULL,undefined),
('Vietnam',NULL,undefined),
('Philippines',NULL,undefined),
('Taiwan',NULL,undefined),
('Ningbo',NULL,undefined),
('East China',NULL,undefined),
('China',NULL,undefined),
('South China',NULL,undefined),
('Korea',NULL,undefined),
('Far East',NULL,undefined),
('Japan',NULL,undefined),
('North China',NULL,undefined),
('Australia',NULL,undefined),
('Cape laden',NULL,undefined),
('Tanzania',NULL,undefined),
('Singapore ballast',NULL,undefined),
('Singapore laden',NULL,undefined),
('Port Louis ballast',NULL,undefined),
('Port Louis laden',NULL,undefined),
('Malaysia ballast',NULL,undefined),
('Malaysia laden',NULL,undefined),
('Cape ballast',NULL,undefined),
('Australia',NULL,undefined),
('Indo',NULL,undefined),
('Thailand',NULL,undefined),
('Vietnam',NULL,undefined),
('Philippines',NULL,undefined),
('Taiwan',NULL,undefined),
('East China',NULL,undefined),
('China',NULL,undefined),
('Ningbo',NULL,undefined),
('South China',NULL,undefined),
('North China',NULL,undefined),
('Korea',NULL,undefined),
('Far East',NULL,undefined),
('Japan',NULL,undefined),
('WCI',NULL,undefined),
('ECI',NULL,undefined),
('Galle',NULL,undefined),
('Open AG',NULL,undefined),
('Richards Bay',NULL,undefined),
('Bahamas',NULL,undefined),
('Mexico',NULL,undefined),
('Cayman',NULL,undefined),
('BVI',NULL,undefined),
('Quintero',NULL,undefined),
('Brazil',NULL,undefined),
('Mohammedia',NULL,undefined),
('Gibraltar',NULL,undefined),
('Flushing',NULL,undefined),
('Turkey',NULL,undefined),
('Eu',NULL,undefined),
('Greece',NULL,undefined),
('East Med',NULL,undefined),
('Suez',NULL,undefined),
('Ocoa',NULL,undefined),
('loads Prince Rupert',NULL,undefined)
ON DUPLICATE KEY UPDATE days=VALUES(days);

CREATE TABLE IF NOT EXISTS discharge_settings (id INT AUTO_INCREMENT PRIMARY KEY, area_name VARCHAR(255) UNIQUE, discharge_days INT DEFAULT 4);
INSERT INTO discharge_settings (area_name, discharge_days) VALUES
('Japan',3),
('Korea',4),
('South Korea',3),
('Far East',5),
('East China',4),
('North China',3),
('South China',3),
('China',3),
('Taiwan',3),
('Indo',3),
('Vietnam',3),
('Thailand',3),
('Malaysia ballast',3),
('Malaysia laden',3),
('Philippines',3),
('Singapore ballast',3),
('Singapore laden',3),
('Australia',3),
('Darwin',3),
('Botany',3),
('AG',3),
('Oman',3),
('Open AG',3),
('ECI',5),
('WCI',5),
('Bangladesh',5),
('Galle',5),
('Eu',4),
('Flushing',4),
('Terneuzen',4),
('East Med',4),
('Turkey',4),
('Gibraltar',4),
('Greece',4),
('Mohammedia',4),
('Algeria',4),
('USG',4),
('Open USG',4),
('Mexico',4),
('Caribs',4),
('Bahamas',4),
('WAF',4),
('Richards Bay',4),
('Tanzania',4),
('Brazil',4),
('Chile',4),
('Santos',4),
('Cape ballast',4),
('Cape laden',4),
('Suez',4),
('loads AG',3),
('loads USG',4),
('loads Prince Rupert',3),
('loads WAF',4),
('Panama',4),
('Corpus Christi',4),
('Marcus Hook',4),
('Cayman',4),
('Ocoa',4),
('Bunker in Jamaica',4),
('USG-Far East',4)
ON DUPLICATE KEY UPDATE discharge_days=VALUES(discharge_days);

CREATE TABLE IF NOT EXISTS port_areas (id INT AUTO_INCREMENT PRIMARY KEY, location_name VARCHAR(255), area VARCHAR(255), region VARCHAR(255), UNIQUE KEY uq_loc (location_name));
INSERT INTO port_areas (location_name, area, region) VALUES
('Sunoco Nederland Terminal','USG',NULL),
('Galveston Light.','USG',NULL),
('Cole Bay','USG',NULL),
('Caribbean Netherlands','USG',NULL),
('Freeport Texas','USG',NULL),
('Houston','USG',NULL),
('Enterprise Houston','USG',NULL),
('Energy Transfer Nederland LPG','Corpus Christi',NULL),
('Buckeye Texas Hub Terminal','USG-Far East',NULL),
('Energy Transfer Marcus Hook','USG',NULL),
('USGC (US Gulf Coast)','USG',NULL),
('loads USG','USG',NULL),
('Americas','USG',NULL),
('Texas','USG',NULL),
('Beaumont/Port Arthur','USG',NULL),
('Tsugaru Strait','Japan',NULL),
('USHOU LA.','USG',NULL),
('US HOU>EG PSD','USG',NULL),
('NEDERL','USG',NULL),
('TEXAS CITY TX','USG',NULL),
('TEXAS CITY','USG',NULL),
('FPT USA','USG',NULL),
('FREEPQLVESTON','USG',NULL),
('HOUSTMS>0751','USG',NULL),
('NEDERLAND, US','USG',NULL),
('HOU,US','USG',NULL),
('PABLB>USHOU','USG',NULL),
('PA BLB > US HOU','USG',NULL),
('Gulf Coast Ammonia','USG',NULL),
('US NDD','USG',NULL),
('DO SPM>US FPO','USG',NULL),
('USHOU\" MEADOW,LA.','USG',NULL),
('TARGA TERMINAL','USG',NULL),
('USHOU BAYTOWN','USG',NULL),
('Buckeye Texas Hub','USG',NULL),
('NEDERLAND. USA','USG',NULL),
('KRTSN->PABLB','USG',NULL),
('BASF Freeport','USG',NULL),
('PADD 5','USG',NULL),
('Honolulu','USG',NULL),
('Phillips 66 Freeport Marine Terminal','USG',NULL),
('ConocoPhillips Teesside Refinery','USG',NULL),
('HOUSTON UP','USG',NULL),
('US RV BUNKERING','USG',NULL),
('Corpus Christi','USG',NULL),
('US GALVESTON','USG',NULL),
('PA BLB >> US NDX','USG',NULL),
('USHOU IRU REFINING','USG',NULL),
('MARCUS HOOK USA','USG',NULL),
('United States','USG',NULL),
('US HOU \"9P','USG',NULL),
('FREE PORT','USG',NULL),
('NEDERLAND, USA','USG',NULL),
('US NDZ3','USG',NULL),
('GOLA,USA','USG',NULL),
('HOU US','USG',NULL),
('US-HOU','USG',NULL),
('HOUSTL>US^0QRX','USG',NULL),
('US FPL LMR','USG',NULL),
('HOUSTON US','USG',NULL),
('US HOU #VV','USG',NULL),
('PA GTN>US HOU','USG',NULL),
('US CRP','USG',NULL),
('USG','USG',NULL),
('Southern Louisiana','USG',NULL),
('US HOU B0QS1','USG',NULL),
('US NDX','USG',NULL),
('NEDERLAND','USG',NULL),
('KR YOS>US','USG',NULL),
('US HOWN REFINING','USG',NULL),
('NEDERLAND USA','USG',NULL),
('PA BLB>US MAH','USG',NULL),
('NEDERLAND US','USG',NULL),
('US HOS','USG',NULL),
('Bay Area Houston','USG',NULL),
('USHOU','USG',NULL),
('US HOU','USG',NULL),
('HOUSTON-USA','USG',NULL),
('US HOUS','USG',NULL),
('USHOUS #IUM','USG',NULL),
('US HOTTX','USG',NULL),
('PA BLB > US NDX','USG',NULL),
('HOUSTON,TX.','USG',NULL),
('US HOU > PA CTB','USG',NULL),
('USHOU PLT STN','USG',NULL),
('MAMOH>USHOU (7NO','USG',NULL),
('USOGL','USG',NULL),
('USFRP','USG',NULL),
('FREEPORT-USA','USG',NULL),
('US LCH','USG',NULL),
('US SBP','USG',NULL),
('US HOTCITY','USG',NULL),
('FREEPORT USA','USG',NULL),
('USMAH','USG',NULL),
('Lake Charles','USG',NULL),
('US HOWEA','USG',NULL),
('US HOU <> US GRY','USG',NULL),
('>US NDX','USG',NULL),
('P66 Freeport','USG',NULL),
('USFPO','USG',NULL),
('HOUSTON USA','USG',NULL),
('HOUSTON TX','USG',NULL),
('US GLS','USG',NULL),
('CNZOS>PABLB','USG',NULL),
('USHOU#','USG',NULL),
('HOUSTON TEXAS','USG',NULL),
('PABLB>USFPO','USG',NULL),
('US NED','USG',NULL),
('USNDX','USG',NULL),
('MARCUS HOOK','USG',NULL),
('BGN 16-30 Jan USG','USG',NULL),
('FREEPORT','USG',NULL),
('IDTSE>USHOU','USG',NULL),
('PABAL>USHOU','USG',NULL),
('FREEPORT US','USG',NULL),
('USFPO ILE CUT GALVES','USG',NULL),
('PADD 3','USG',NULL),
('Sabine Pass','USG',NULL),
('Energy Transfer Nederland Terminal','USG',NULL),
('PORT EVERGLADES','USG',NULL),
('USHOU #','USG',NULL),
('MAMOH USHOU','USG',NULL),
('US_GLS','USG',NULL),
('USHOU#N','USG',NULL),
('CORPUS','USG',NULL),
('HOUSTON,USA','USG',NULL),
('CRIST0BAL','USG',NULL),
('Northern America','USG',NULL),
('NEDUS','USG',NULL),
('US BPT','USG',NULL),
('HOUSTON #NY','USG',NULL),
('Energy Transfer Nederland','USG',NULL),
('PORT NECHES TX','USG',NULL),
('USA-FREEPORT','USG',NULL),
('US NEDERLAND','USG',NULL),
('US FREEPORT','USG',NULL),
('N. Atlantic','USG',NULL),
('PHILADELPHIA','USG',NULL),
('GALVESTON','USG',NULL),
('HOUSTON, USA','USG',NULL),
('US FPT','USG',NULL),
('USBPT','USG',NULL),
('PR CTBLINE LOGISTICS','USG',NULL),
('PA CTB > UPX # ND','USG',NULL),
('PA BLB>US HOU','USG',NULL),
('US HOUR CUT','USG',NULL),
('USFPO-GBIMM','USG',NULL),
('NEDERLAND, U.S.A','USG',NULL),
('US GOLUSHOU','USG',NULL),
('USGLS<>USHOU','USG',NULL),
('U<HKOU','USG',NULL),
('PA CTB > US NDX','USG',NULL),
('US MAH','USG',NULL),
('PA CTB > H','USG',NULL),
('USHOU MAMOH','USG',NULL),
('HOUSTO BAYOU','USG',NULL),
('US HOW5 GALVESTON','USG',NULL),
('MARCUS HOOK US','USG',NULL),
('HOUSTON,TX','USG',NULL),
('US HOUSTON','USG',NULL),
('US HOWN, TX','USG',NULL),
('USHOU ES','USG',NULL),
('NEDERLAND,U.S.A','USG',NULL),
('FREEPORT TX','USG',NULL),
('HOUSTN','USG',NULL),
('Aruba','Caribs',NULL),
('CITGO Aruba Refinery','Caribs',NULL),
('Kingston LPG','Caribs',NULL),
('Kingston LPG Terminal','Caribs',NULL),
('St. Thomas','Caribs',NULL),
('Bonaire Sint Eustatius','Cayman',NULL),
('Cayman Islands','Cayman',NULL),
('Georgetown','Ocoa (as proxy)',NULL),
('Dominican Republic','Ocoa',NULL),
('Ocoa Bay Anchorage','Ocoa (as proxy)',NULL),
('Caribbean Sea','Ocoa (as proxy)',NULL),
('SAN PEDRO','Ocoa',NULL),
('San Pedro de Macoris LPG Terminal','Ocoa',NULL),
('San Pedro de Macoris LPG','Ocoa',NULL),
('OCOA BAY','Ocoa (as proxy)',NULL),
('Curacao','Ocoa',NULL),
('Kingston','Ocoa',NULL),
('CA PRR','Ridley->Far East + 14',NULL),
('Ridley Island Terminal','Ridley->Far East + 14',NULL),
('Ridley Island Propane Export Terminal','Ridley->Far East + 14',NULL),
('Canada','Ridley->Far East + 14',NULL),
('Ferndale','+14 days open Far East',NULL),
('USWC (US West Coast)','+14 days open Far East',NULL),
('Cherry Point','Ferndale->Far East + 14',NULL),
('Balboa','Panama',NULL),
('Panama LNG','Panama',NULL),
('PA CRI','Panama',NULL),
('> PA CRI','Panama',NULL),
('BLB PA','Panama',NULL),
('PNBLB','Panama',NULL),
('PN BLB','Panama',NULL),
('PACBL','Panama',NULL),
('PACR','Panama',NULL),
('Cristobal Light.','Panama',NULL),
('Panama Canal Light.','Panama',NULL),
('Black Sea','Panama',NULL),
('Panama Canal','Panama',NULL),
('CRSTBL','Panama',NULL),
('Panama','Panama',NULL),
('PABLB W TPE','Panama',NULL),
('PR CTB 28','Panama',NULL),
('PA CBL','Panama',NULL),
('CTB PA','Panama',NULL),
('Bahia Las Minas Refineria','Marcus Hook',NULL),
('PABLB','Panama',NULL),
('Energy Transfer Marcus Hook Refinery','Marcus Hook',NULL),
('Sunoco Marcus Hook Refinery','Marcus Hook',NULL),
('Freeport Bahamas','Bahamas',NULL),
('Tuxpan Gas Tomza','Bunker in Jamaica',NULL),
('Come By Chance Refinery','DD in AG',NULL),
('MIDDLE EAST REGION','AG',NULL),
('Drydocks World – Dubai','AG',NULL),
('Saudi Arabia','AG',NULL),
('RAS BUDRAN EGYPT','AG',NULL),
('Karachi Shipyard','AG',NULL),
('AE RUS','AG',NULL),
('Khor Al Zubair Port','AG',NULL),
('AE FJR >>QA RLF','AG',NULL),
('FUJAIRAH UAE','AG',NULL),
('MESAIEED_QATAR','AG',NULL),
('RAS LAFFAN QATAR R','AG',NULL),
('RAS_LAFFAN','AG',NULL),
('QA UMS','AG',NULL),
('RAS LAFFAN QATAR 1L','AG',NULL),
('MINA BAN','AG',NULL),
('THSRI>AEFUJ','AG',NULL),
('Oiltank. Sohar','AG',NULL),
('SOHAR OMAN','AG',NULL),
('Saudi Aramco Ras Tanura LPG Terminal','AG',NULL),
('MAA KUWAIT','AG',NULL),
('KU MAA HY','AG',NULL),
('MINA AL AHMADY','AG',NULL),
('AE FJR>KW MEA','AG',NULL),
('ID TSE TO QA RLF','AG',NULL),
('SA RTAHEEN FIELD','AG',NULL),
('Ras Al Khair','AG',NULL),
('KW ME','AG',NULL),
('Mina al-Ahmadi LPG','AG',NULL),
('RASLAFFAN K','AG',NULL),
('Jebel Ali LPG','AG',NULL),
('Qatar Petroleum Ras Laffan Refinery','AG',NULL),
('BHMIN','AG',NULL),
('EG AIRUSORF','AG',NULL),
('RUWAIP','AG',NULL),
('RLF','AG',NULL),
('SGSIN QARLF','AG',NULL),
('AT MAA','AG',NULL),
('MINA AL AHAMADIA','AG',NULL),
('Ju\'aymah NGL','AG',NULL),
('INHAL >QA RLF','AG',NULL),
('KWMEA/MINCUMYA','AG',NULL),
('MINA AL AHMADI KUWAI','AG',NULL),
('AE RUUEH','AG',NULL),
('IN HAL QA RLF','AG',NULL),
('Persian Gulf','AG',NULL),
('RASLAFAN QATAR','AG',NULL),
('AERWP','AG',NULL),
('YANBU KSA','AG',NULL),
('Horizon Djibouti','AG',NULL),
('PK KHI --- AE RUW','AG',NULL),
('SAYBI','AG',NULL),
('AE FJR D ANCHORAGE','AG',NULL),
('QA RLEEH','AG',NULL),
('AEFJR','AG',NULL),
('FUJAIRAH_OPL','AG',NULL),
('Fujairah','AG',NULL),
('RUWAIS,UAE','AG',NULL),
('Advario Oman','AG',NULL),
('IN VTZ - QA RLF','AG',NULL),
('AE FUJ>KW MEA','AG',NULL),
('INHAL > AEFJR','AG',NULL),
('Ruwais Refinery','AG',NULL),
('AEDAS','AG',NULL),
('MINA AI AHMADI','AG',NULL),
('AE DAS','AG',NULL),
('FUJ UAE','AG',NULL),
('AEFJRC','AG',NULL),
('Iraq','AG',NULL),
('RASLAFAN','AG',NULL),
('Jubail Industrial Port','AG',NULL),
('JPOIT K 3 E OFF','AG',NULL),
('Mesaieed','AG',NULL),
('Umm Said','AG',NULL),
('Khor Fakkan Anchorage','AG',NULL),
('AE_DAS','AG',NULL),
('AERUW','AG',NULL),
('FUJ','AG',NULL),
('ID MRK > AU RUW','AG',NULL),
('AEPRA','AG',NULL),
('SA RTA','AG',NULL),
('FUJAIRAH 3','AG',NULL),
('SA_RTA','AG',NULL),
('AE KLFIELD','AG',NULL),
('QARLF!N','AG',NULL),
('SA RT','AG',NULL),
('QARLD','AG',NULL),
('RLF Q','AG',NULL),
('AG','AG',NULL),
('AERWS','AG',NULL),
('RAS LAFFAN,QATAR','AG',NULL),
('SGSIN>KWMEA','AG',NULL),
('AE FJR>>QA RLF','AG',NULL),
('SA TRA','AG',NULL),
('ASRY','AG (Baharin DD, Gas Alkhaleej)',NULL),
('Ras Laffan Refinery','AG',NULL),
('Das Island Products','AG',NULL),
('BAPCO Sitra Refinery','AG',NULL),
('QARLF#0','AG',NULL),
('AE KLF > KW MEA','AG',NULL),
('QA RALF','AG',NULL),
('SGSIN > QARLF','AG',NULL),
('MMA,KUWAIT','AG',NULL),
('United Arab Emirates','AG',NULL),
('Gulf of Oman','AG',NULL),
('QA RLD','AG',NULL),
('Duqm','AG',NULL),
('KW MAA','AG',NULL),
('SA JUT #?&','AG',NULL),
('RAS LAFFAN \"&;','AG',NULL),
('Oiltanking Odfjell Terminal Oman','AG',NULL),
('Kuwait','AG (MAA)',NULL),
('Jubail Refinery','AG',NULL),
('Qatar','AG',NULL),
('KR YOS > KE MEA','AG',NULL),
('IN HAL> AE FUJ','AG',NULL),
('KHORFAKAN','AG',NULL),
('Mina\' Saqr','AG',NULL),
('DAS ISLAND, U.A.E','AG',NULL),
('Sharjah Anchorage','AG',NULL),
('Horizon Djibouti Terminal','AG',NULL),
('Oman','AG',NULL),
('AE RWS','AG',NULL),
('ASRY,BAHARIN ES','AG',NULL),
('MEA KUW','AG',NULL),
('Asaluyeh South Pars Terminal','AG',NULL),
('ASRY M','AG',NULL),
('Sitra Refinery','AG',NULL),
('ASRY,BAHARIN #;\\','AG',NULL),
('IN HAL>>RUWAIP','AG',NULL),
('ASRY BEERA PORT','AG',NULL),
('RAS TANNURAH.KSA','AG',NULL),
('Yanbu NGL Terminal','AG',NULL),
('QA RLF','AG',NULL),
('AEFJR>KWMEA','AG',NULL),
('INDAH KWMEA','AG',NULL),
('RAS LAFAN','AG',NULL),
('AE FUJ AE KLF GE','AG',NULL),
('RAS LAFFAN','AG',NULL),
('AE RWP >','AG',NULL),
('FUJAIRAHX','AG',NULL),
('FUJAIRAH D ANCR','AG',NULL),
('SA RTAFFAN','AG',NULL),
('HAMRIYAH.U.A.E.','AG',NULL),
('IN HAL > AE FJ','AG',NULL),
('KHORFAKKAN','AG',NULL),
('QA RLE','AG',NULL),
('KU MAA','AG',NULL),
('OPL FUJAIRAH','AG',NULL),
('AE RWP','AG',NULL),
('Yanbu NGL & Yasref','AG',NULL),
('Khasab Anchorage','AG',NULL),
('ARMED GUARDS ONBOARD','AG',NULL),
('RUWAIS','AG',NULL),
('RAS LAFFAN, QATAR','AG',NULL),
('Mina Al-Ahmadi','AG',NULL),
('Middle East','AG',NULL),
('Mideast Gulf','AG',NULL),
('JEBEL ALI','AG',NULL),
('RUWAIS^5E5E5E5E5E5E5','AG',NULL),
('QARFL','AG',NULL),
('QARLF','AG',NULL),
('RAS LAFFAN\\QATAR','AG',NULL),
('AE RUW','AG',NULL),
('>FUJ','AG',NULL),
('SGSIN >> AEFJR','AG',NULL),
('INHAL > AEDAS','AG',NULL),
('AE FJR','AG',NULL),
('RUWAIS UAE','AG',NULL),
('AG FOR ORDERS','AG',NULL),
('KWMEA','AG',NULL),
('FUJAIRAH,UAE','AG',NULL),
('East Coast UAE - Fujairah','AG',NULL),
('Sitra','AG',NULL),
('DUBAI OPL','AG',NULL),
('IN HAL >AE-FJR','AG',NULL),
('DUQM, OMAN','AG',NULL),
('BH SIT','AG',NULL),
('ID MRK-AE FJR','AG',NULL),
('IN HAL >> AE FUJ','AG',NULL),
('Red Sea','AG',NULL),
('DUBAI','AG',NULL),
('QA RUS','AG',NULL),
('AE FJR >> KW MAA','AG',NULL),
('KHASAB','AG',NULL),
('SHARJAH','AG',NULL),
('RASTANURAH','AG',NULL),
('RASLAFFAN QATAR','AG',NULL),
('ASRY FAN QATAR','AG',NULL),
('DASISLAND','AG (Iran)',NULL),
('YOSU,SOUTH KOREA','AG',NULL),
('AE JEA > AE FJR','AG',NULL),
('QA QLF','AG',NULL),
('RAS TANURA','AG',NULL),
('AEF-JR','AG',NULL),
('QA RLF S','AG',NULL),
('SA YNB','AG',NULL),
('RUWAIS FOR ORDERS','AG',NULL),
('SARTA','AG',NULL),
('RAS LAN','AG',NULL),
('MINA ALAHMADI','AG',NULL),
('SGSIN > AEFJR','AG',NULL),
('SA YNB>SA GIZ','AG',NULL),
('QR RLF','AG',NULL),
('RAS LABAI','AG',NULL),
('Iran','AG',NULL),
('Yanbu NGL & Yanbu Aramco Sinopec Refining Company','AG',NULL),
('Ras Tanura LPG','AG',NULL),
('RUW UAE','AG',NULL),
('INHAL > AEFUJ','AG',NULL),
('SOHAR','AG',NULL),
('KWMEA #UMYA','AG',NULL),
('RAS LAFFAN BC O>U','AG',NULL),
('AE FUJ','AG',NULL),
('AE DAS > AE RUW','AG',NULL),
('AE RUW>>OM SOH','AG',NULL),
('QA MES','AG',NULL),
('MINA AL AHAMEDI','AG',NULL),
('MINAALAHMADI','AG',NULL),
('West Coast UAE','AG',NULL),
('KWMEA\"','AG',NULL),
('RASLAFFAN.QATAR','AG',NULL),
('ASRY,BAHARIN IJ','AG',NULL),
('QA RAS','AG',NULL),
('MINA AL AH','AG',NULL),
('DDW-D','AG (DD)',NULL),
('AE PRA','AG (DD, Kodaijisan)',NULL),
('AE FJR>AE DXB','AG (DD)',NULL),
('AE DXB','AG ( DD, BW Trader)',NULL),
('PORTSAID,EGYPT','Suez + 7',NULL),
('RAS GHARIB','Suez + 7',NULL),
('SUMED EGYPT','Suez + 7',NULL),
('Suez Canal','Suez + 7',NULL),
('OPL SUEZ','Suez + 7',NULL),
('SUEZ STS AREA','Suez + 7',NULL),
('IDBDJ>EGADA','Suez + 7',NULL),
('EG WAF','Suez + 7',NULL),
('Suez','ECI + 5',NULL),
('EG SZC','Suez + 7',NULL),
('AINSUKHANA','Suez + 7',NULL),
('Ain Sukhna','Suez + 7',NULL),
('Port Said','Suez + 7',NULL),
('Egypt','Suez + 7',NULL),
('EGDAM','Suez + 7',NULL),
('Alexandria','Suez + 7',NULL),
('El Dekheila','Suez + 7',NULL),
('South Suez Canal','Suez + 7',NULL),
('ABO RUDIS','Suez + 7',NULL),
('SA RTA SA JH','Suez + 7',NULL),
('Alexandria Products Import Terminal','Suez + 7',NULL),
('Wadi Feiran LGP Terminal','Suez + 7',NULL),
('SUEZ, EGYPT','Suez + 7',NULL),
('Gulf of Aqaba','Suez + 7',NULL),
('Ain Sukhna 2','Suez + 7',NULL),
('WADIFEIRAN','Suez + 7',NULL),
('WADI FAYRAN,EG','Suez + 7',NULL),
('SUEZ EGYPT','Suez + 7',NULL),
('EGSCN','Suez + 7',NULL),
('Damietta','Suez + 7',NULL),
('EGSUZ > SAGIZ','Suez + 7',NULL),
('Port of Suez','Suez + 7',NULL),
('RAS BVDRAN','Suez + 7',NULL),
('SUEZ OPL EGYPT','Suez + 7',NULL),
('WADI ETI','Suez + 7',NULL),
('SUEZ OPL','Suez + 7',NULL),
('US NDX>EG SUZ','Suez + 7',NULL),
('EG SUZ','Suez + 7',NULL),
('EGSUZ','Suez + 7',NULL),
('EGWAF','Suez + 7',NULL),
('EG PSD>EG SUZ','Suez + 7',NULL),
('EG AIS','Suez + 7',NULL),
('EGAIS','Suez + 7',NULL),
('SAGIZ','Suez + 7',NULL),
('SUMED. PEBGA','Suez + 7',NULL),
('RAS SHUQIR','Suez + 7',NULL),
('WADI EAYQAN,EF','Suez + 7',NULL),
('WADI FEIRAN','Suez + 7',NULL),
('AIN SUKHNAH','Suez + 7',NULL),
('SA RTA>SA GIZ','Suez + 7',NULL),
('RAS BUDRAN','Suez + 7',NULL),
('Jizan Refinery','Suez + 7',NULL),
('SA GIZ','Suez + 7',NULL),
('JIZAN OPL','Suez + 7',NULL),
('Sonker Ain Sukhna','Suez + 7',NULL),
('Port Qasim','Suez + 7',NULL),
('Red Sea Light.','Suez + 7',NULL),
('WADI FERAN','Suez + 7',NULL),
('AIN SUKHNA EGYPT','Suez + 7',NULL),
('SUEZE GYPT','Suez + 7',NULL),
('JIZAN','Suez + 7',NULL),
('PORT SAID EGYPT','Suez + 7',NULL),
('EGSZC','Suez + 7',NULL),
('Jordan','Suez + 7',NULL),
('Wadi Feiran LPG','Suez + 7',NULL),
('EG_AIS','Suez + 7',NULL),
('JIZAN_ARMEDGUARD','Suez + 7',NULL),
('Aqaba Terminal','Suez + 7',NULL),
('EG RAB','Suez + 7',NULL),
('AINSUKHNA','Suez + 7',NULL),
('ABU RUDEIS','Suez + 7',NULL),
('SG SIN - EG SUZ','Suez + 7',NULL),
('EGYPT SUEZ','Suez + 7',NULL),
('(SUEZ)','Suez + 7',NULL),
('Ain Sukhna Ammonia','Suez + 7',NULL),
('SUEZ SOUTH STS','Suez + 7',NULL),
('EG SCZ','Suez + 7',NULL),
('EAST COAST SAUDI ARABIA','AG',NULL),
('Las Palmas','Canary Islands',NULL),
('Arzew','Bethioua -> SG',NULL),
('USHOU>MAMNY','Mohammedia + 5',NULL),
('DZ AZW','Mohammedia + 5',NULL),
('Algeria','Mohammedia + 5',NULL),
('Skikda','Mohammedia + 5',NULL),
('MOHAMMEDIA','Mohammedia + 5',NULL),
('Samir Mohammedia Refinery','Mohammedia',NULL),
('MA JFL','Mohammedia + 5',NULL),
('MA MOH','Mohammedia + 5',NULL),
('Mohammedia Refinery','Mohammedia + 5',NULL),
('ESALG>MAML','Mohammedia + 5',NULL),
('MOHMMEDIA','Mohammedia + 5',NULL),
('Talara Refinery','Mohammedia + 5',NULL),
('Sanha FPSO','WAF',NULL),
('Western Africa','WAF',NULL),
('Tema Oil Refinery','WAF',NULL),
('Soyo Condensate terminal','WAF',NULL),
('Bonny LPG','WAF (Soyo)',NULL),
('Escravos Terminal','WAF',NULL),
('Nigeria','WAF',NULL),
('Angola','WAF',NULL),
('LUANDA 0(\"H','WAF',NULL),
('AO LAD','WAF',NULL),
('Luanda Refinery','WAF',NULL),
('FPSO_SANHA','WAF',NULL),
('Pointe Noire Terminal','WAF',NULL),
('N\'Kossa FPSO','WAF',NULL),
('SANHA FSO','WAF',NULL),
('SANHA ANGOLA','WAF',NULL),
('SOYO','WAF',NULL),
('NGESC','WAF',NULL),
('BONNY','WAF',NULL),
('TG TFW>NG ESC','WAF',NULL),
('Escravos Offshore Terminal','WAF',NULL),
('Onne','WAF',NULL),
('ESCRAVOS','WAF',NULL),
('NG ESC','WAF',NULL),
('Durban LPG','WAF',NULL),
('Pointe Noire','WAF',NULL),
('Richards Bay','Richards Bay',NULL),
('ZA PLZ>ZA RCB','WAF',NULL),
('ZARCB','WAF',NULL),
('NG ESC FSO','WAF',NULL),
('PlusPetrol Pisco','WAF',NULL),
('LUANDA','WAF',NULL),
('US HOU ZA RCB','WAF',NULL),
('Walvis Bay','WAF (discharge)',NULL),
('SANHA','WAF',NULL),
('Lome','WAF',NULL),
('Bioko','WAF',NULL),
('ESCRAVOS NIGERIA','WAF',NULL),
('BONNY NIGERIA','WAF',NULL),
('LUAND','WAF',NULL),
('SANHA,ANGOLA','WAF',NULL),
('Bata','Cape',NULL),
('Alba LPG Plant','Cape',NULL),
('Port Elizabeth','Cape (as proxy)',NULL),
('Durban','Cape (as proxy)',NULL),
('Cape Town','Cape (as proxy)',NULL),
('Richards Bay Bidvest Terminal','Cape (as proxy)',NULL),
('Durban LPG Terminal','Beira (Mozambique, East Africa)',NULL),
('Petredec Mauritius','Cape',NULL),
('Port Louis','Port Louis',NULL),
('PORT ELZBTH','Cape',NULL),
('BP Beira Products Terminal','Cape',NULL),
('ZA RCB > ZA CPT','Cape',NULL),
('ZA PLZ','Cape',NULL),
('MU PLU','Tanzania + 7',NULL),
('ZNZ','Tanzania + 7',NULL),
('TZZNZ','Tanzania + 7',NULL),
('Cape of Good Hope','Tanzania + 7',NULL),
('COEGA','Tanzania + 7',NULL),
('South Africa','Tanzania + 7',NULL),
('Eastern Africa','Tanzania + 7',NULL),
('Tanzania','Tanzania + 7',NULL),
('Tanzania International Petroleum Reserves','Tanzania + 7',NULL),
('MBSA','Tanzania + 7',NULL),
('Mombasa','Tanzania + 7',NULL),
('MU PLU>ZA RCB','Tanzania + 7',NULL),
('ZA RCB,SOUTH AFRICA','Tanzania + 7',NULL),
('ZA RCB','Tanzania + 7',NULL),
('TZ ZNZ','Tanzania + 7',NULL),
('ZANZIBAR','Tanzania + 7',NULL),
('Kenya','Tanzania + 7',NULL),
('Nipah Light.','Singapore',NULL),
('SPORE PWBGA','Singapore',NULL),
('SGSIN PEBGB','Singapore',NULL),
('NG ESC>SG SIN','Singapore',NULL),
('Pelepas Light.','Singapore',NULL),
('Singapore Strait','Singapore',NULL),
('SPORE','Singapore',NULL),
('SGSJN','Singapore',NULL),
('SG SINANG','Singapore',NULL),
('Singapore','Singapore',NULL),
('Singapore Republic','Singapore',NULL),
('SG PBGB','Singapore',NULL),
('SG SIN (PEBGA)','Singapore',NULL),
('SGSIN ASSPU','Singapore',NULL),
('SGSIN','Singapore',NULL),
('SINGAPORE-HORIZON','Singapore',NULL),
('Sudong','Singapore',NULL),
('SG WPBGA','Singapore',NULL),
('SG SILPWBGA','Singapore',NULL),
('PJSB SINGAPORE','Singapore',NULL),
('SG SIOGSIN','Singapore',NULL),
('ASSPU ANCHORAGE','Singapore',NULL),
('Malacca Strait','Singapore (DD)',NULL),
('KRINC ASSPU SIN','Singapore (DD)',NULL),
('KEPPEL','Singapore (DD)',NULL),
('SG-SIN/ASSPU','Singapore',NULL),
('SG-PGBG','Singapore',NULL),
('SG SIN PWBGA','Singapore',NULL),
('SG SIG','Singapore',NULL),
('SGSIG-PGBG','Singapore',NULL),
('SG SIN PGBG','Singapore',NULL),
('SGSIN PWBGA','Singapore',NULL),
('SG-PG','Singapore',NULL),
('SGSIN YTRDK','Singapore',NULL),
('NIPAH,ORE PEBGC','Singapore',NULL),
('SGSIG PGBG','Singapore',NULL),
('Huchem Bintulu Ammonia','Singapore',NULL),
('SNG','Singapore',NULL),
('PEBG','Singapore (M\'sia)',NULL),
('SG SIN KEPPEL','Singapore (DD)',NULL),
('Western Petroleum B Anchorage','Singapore (DD)',NULL),
('SIN TUAS DD','Singapore (DD)',NULL),
('SG KEQRTH','Singapore (DD)',NULL),
('Johor Port Berhad','Singapore (DD)',NULL),
('Semabawang','Singapore',NULL),
('Tanjung Sulong','Load Msia - Disch South/East China likely',NULL),
('ATB','Singapore',NULL),
('KR MOK TO SG SIN','Singapore',NULL),
('Bintulu','Singapore',NULL),
('Johor Port','Malaysia',NULL),
('Kuantan','Malaysia',NULL),
('Westport','Malaysia (bunkers)',NULL),
('Petronas PBCT terminal','Malaysia + 2',NULL),
('Rapid','Malaysia',NULL),
('Malaysia - Malacca Strait','Malaysia',NULL),
('Stolthaven Westport Klang Terminal','Malaysia + 2',NULL),
('Sabah Ammonia Urea Terminal','Malaysia + 2',NULL),
('Malaysia','Malaysia',NULL),
('Petronas Melaka Refinery','Malaysia + 2',NULL),
('Far East','Far East',NULL),
('Eastern Asia','India?/SG-JP?',NULL),
('Asia','Far East',NULL),
('Taipei','Taiwan + 2',NULL),
('Shen-ao Oil Harbour','Taiwan + 2',NULL),
('Talin Refinery','Taiwan + 2',NULL),
('Talin Products Terminal','Taiwan + 2',NULL),
('Taichung LPG','Taiwan + 2',NULL),
('Kaohsiung','Taiwan + 2',NULL),
('Taichung LPG Terminal','Taiwan + 2',NULL),
('Taiwan','Taiwan + 2',NULL),
('Mailiao','Taiwan + 2',NULL),
('Talin Products','Taiwan + 2',NULL),
('Shen-ao','Taiwan + 2',NULL),
('Dongjiakou','North China +4',NULL),
('Rizhao','North China +4',NULL),
('Binzhou','North China +4',NULL),
('Huludao','North China +4',NULL),
('Bora LyondellBasell Panjin Cracker','North China +4',NULL),
('Laoining Kingfa Cracker','North China +4',NULL),
('Shandong','North China +4',NULL),
('North China','North China +4',NULL),
('Zhifu','North China +4',NULL),
('Dalian LPG','North China +4',NULL),
('Yantai LPG','North China +4',NULL),
('Yantai LPG Terminal','North China +4',NULL),
('Yantai Area','North China +4',NULL),
('Longkou Port','North China +4',NULL),
('Tianjin','North China +4',NULL),
('Vopak Terminal Tianjin Lingang','North China +4',NULL),
('Rizhao Area','North China +4',NULL),
('Dalian Fujia','North China +4',NULL),
('Indo','North China +4',NULL),
('Longkou LPG','North China +4',NULL),
('Longkou','North China +4',NULL),
('Panjin','North China +4',NULL),
('Tianjin Anchorage','North China +4',NULL),
('Vopak Tianjin Lingang','North China +4',NULL),
('Qingdao','North China +4',NULL),
('Liaoning Kingfa Cracker','North China +4',NULL),
('CN PAJ','North China +4',NULL),
('Lianyungang Petrochemical Storage','North China +4',NULL),
('Lianyungang','North China +4',NULL),
('Qingdao Huangdao','North China +4',NULL),
('Wanhua Yantai NGL Terminal','North China +4',NULL),
('Dongying LPG','North China +4',NULL),
('Sinopec Hainan','South China + 4',NULL),
('Hainan','South China + 4',NULL),
('Dongshan Bay','South China + 4',NULL),
('Shenzhen LPG','South China + 4',NULL),
('Gaolan Siamgas','South China + 4',NULL),
('Guangzhou','South China + 4',NULL),
('Qinzhou LPG','South China + 4',NULL),
('Guangdong Area','South China + 4',NULL),
('Nansha','South China + 4',NULL),
('Chaozhou','South China + 4',NULL),
('Shenzhen LPG Terminal','South China + 4',NULL),
('Fangcheng','South China + 4',NULL),
('CN SHG HRDD','South China + 4',NULL),
('Sinopec Fujian','South China + 4',NULL),
('Shenzhen','South China + 4',NULL),
('Raoping','South China + 4',NULL),
('Min Jiang','South China + 4',NULL),
('Hong Kong Port','South China + 4',NULL),
('Fujian','South China + 4',NULL),
('Haikou LPG','South China + 4',NULL),
('CNFZG','South China + 4',NULL),
('Hong Kong','South China + 4',NULL),
('Sinochem Quanzhou Petrochemical','South China + 4',NULL),
('FREP Plant','South China + 4',NULL),
('South China','South China + 4',NULL),
('South China Sea','South China + 4',NULL),
('Fuzhou','South China + 4',NULL),
('Fuzhou Chemicals','South China + 4',NULL),
('Huizhou Petrochemicals','South China + 4',NULL),
('Guangdong','South China + 4',NULL),
('Qinzhou','South China + 4',NULL),
('Shantou','South China + 4',NULL),
('Chiwan Petroleum','South China + 4',NULL),
('Guangzhou Area','South China + 4',NULL),
('Dongshan LPG','South China + 4',NULL),
('Zhu Hai','South China + 4',NULL),
('Yiulian Shipyard','Dry dock',NULL),
('Sinopec Zhanjiang Dongxing Refinery','South China + 4',NULL),
('Zhanjiang','South China + 4',NULL),
('BASF Zhanjiang Verbund','South China + 4',NULL),
('Jingjiang LPG','East China + 4',NULL),
('Tongshouwei Shipyard','Dry Dock',NULL),
('Yellow Sea','East China + 4',NULL),
('Taixing','East China + 4',NULL),
('Daxie Ningbo LPG','East China + 4',NULL),
('Daxie Ningbo','East China + 4',NULL),
('Ningbo Area','East China + 4',NULL),
('Chongming','East China + 4',NULL),
('Ningbo','East China + 4',NULL),
('Jiangyin Lyon','East China + 4',NULL),
('Huangyan Shanzui Tou Import Terminal','East China + 4',NULL),
('Zhapu LPG Terminal','East China + 4',NULL),
('Wenzhou','East China + 4',NULL),
('Caojing','East China + 4',NULL),
('Caojing Anchorage','East China + 4',NULL),
('Jinshan Caojing','East China + 4',NULL),
('China','East China + 4',NULL),
('Jiangsu Litian','East China + 4',NULL),
('Qidu','East China + 4',NULL),
('Jiangsu Yangtzejiang Petrochemical','East China + 4',NULL),
('Chang Jiang Kou Anch.','East China + 4',NULL),
('East China','East China + 4',NULL),
('Nantong 2','East China + 4',NULL),
('Zhangjiagang','East China + 4',NULL),
('Shanghai Area','East China + 4',NULL),
('West Pacific Petrochemical Company Refinery','East China + 4',NULL),
('Jiangsu Litian Terminal','East China + 4',NULL),
('Chengxi Shipyard','Dry dock',NULL),
('Jiangyin Chengxi Ship Voyage Repair','East China + 4',NULL),
('Vopak Ningbo','East China + 4',NULL),
('CJK','East China + 4',NULL),
('Shanghai','East China + 4',NULL),
('Shuidong','South China + 3',NULL),
('Dafeng','East China + 4',NULL),
('Yangtze river','East China + 4',NULL),
('Xiaomenyu Port','East China + 4',NULL),
('Huangyan Shanzui Tou','East China + 4',NULL),
('Zhenjiang','East China + 4',NULL),
('Jiangnan Shipyard','Dry dock',NULL),
('Zhapu LPG','East China + 4',NULL),
('Zhoushan','East China + 4',NULL),
('Lujia Shipyard','Dry Dock',NULL),
('East China Sea','East China + 4',NULL),
('Hengli Petrochemical','East China + 4',NULL),
('Sinopec Nanjing','East China + 4',NULL),
('Eastern China Sea','East China + 4',NULL),
('Nanrong Petrochemical Terminal','East China + 4',NULL),
('Gyeongsangnam','Korea + 4',NULL),
('SK Ulsan','Korea + 4',NULL),
('South Korea','Korea + 4',NULL),
('Ulsan','Korea + 4',NULL),
('Incheon LPG','Korea + 4',NULL),
('Yeosu','Korea+3/+1 bunkers',NULL),
('Yeosu Light.','Korea+3/+1 bunkers',NULL),
('SK Gas Pyeongtaek','Korea + 4',NULL),
('Total Daesan Hanwha Refinery','Korea + 4',NULL),
('Ulsan Ammonia Terminal','Korea + 4',NULL),
('SK Ulsan Refinery','Korea + 4',NULL),
('Seetec Daesan','Korea + 4',NULL),
('Busan','Korea + 4',NULL),
('Ulsan Ammonia','Korea + 4',NULL),
('Boryeong','Korea + 4',NULL),
('Boryeong LNG Terminal','Korea + 4',NULL),
('Incheon Port','Korea + 4',NULL),
('Hyundai Daesan Refinery','Korea + 4',NULL),
('Niihama','Japan + 6',NULL),
('Naoetsu INPEX','Japan + 6',NULL),
('Tsuneishi Shipyard','Dry Dock',NULL),
('Sakaide','Japan + 6',NULL),
('Mizushima','Japan + 6',NULL),
('Marifu Refinery','Japan + 6',NULL),
('Matsuura','Japan + 6',NULL),
('Niigata LPG','Japan + 6',NULL),
('Sakai Mitsui Chemicals','Japan + 6',NULL),
('Yokkaichi','Japan + 6',NULL),
('Chiba','Japan + 6',NULL),
('Chiba Area','Japan + 6',NULL),
('Kagoshima','Japan + 6',NULL),
('Showa Kobe','Japan + 6',NULL),
('Imari','Japan + 6',NULL),
('Nagasaki Works','Japan + 6',NULL),
('Sendai Refinery','Japan + 6',NULL),
('Tokuyama','Japan + 6',NULL),
('Hitachi LPG','Japan + 6',NULL),
('Kawasaki','Japan + 6',NULL),
('Japan','Japan + 6',NULL),
('Nagoya','Japan + 6',NULL),
('Aomori','Japan + 6',NULL),
('Negishi LNG Terminal','Japan + 6',NULL),
('Sakaide LPG','Japan + 6',NULL),
('Kashima','Japan + 6',NULL),
('Namikata','Japan + 6',NULL),
('Oita LPG','Japan + 6',NULL),
('Naoetsu INPEX LNG Terminal','Japan + 6',NULL),
('Tokyo Bay','Japan + 6',NULL),
('Kinuura','Japan + 6',NULL),
('Nanao','Japan + 6',NULL),
('Yokkaichi Plant','Japan + 6',NULL),
('Tokuyama LPG Terminal','Japan + 6',NULL),
('Karatsu','Japan + 6',NULL),
('Nisshin Oillio Okayama','Japan + 6',NULL),
('Yokohama','Japan + 6',NULL),
('Kobe','Japan + 6',NULL),
('Oita','Japan + 6',NULL),
('Tokuyama LPG','Japan + 6',NULL),
('Ohgishima LNG Terminal','Japan + 6',NULL),
('Japan Sea','Japan + 6',NULL),
('Himeji','Japan + 6',NULL),
('Joetsu INPEX','Japan + 6',NULL),
('Yokosuka','Japan + 6',NULL),
('Niigata','Japan + 6',NULL),
('Matsuura Kyushu','Japan + 6',NULL),
('Kaita','Japan + 6',NULL),
('Fukuoka LPG Centre','Japan + 6',NULL),
('Iwatani Sakai','Japan + 6',NULL),
('Showa Kobe Terminal','Japan + 6',NULL),
('Hekinan','Japan + 6',NULL),
('Fukuyama','Japan + 6',NULL),
('Visakhapatnam Refinery','ECI + 5',NULL),
('Ennore Fertilizer Plant','ECI + 5',NULL),
('Kakinada Fertilizer','ECI + 5',NULL),
('Petregaz Krishnapatnam','ECI + 5',NULL),
('Paradip','ECI + 5',NULL),
('Ennore','ECI + 5',NULL),
('Ennore Port','ECI + 5',NULL),
('Ennore Terminal','ECI + 5',NULL),
('East Coast India','ECI + 5',NULL),
('Dhamra Anchorage','ECI + 5',NULL),
('Chittagong','\"ECI\" +3 (Bangladesh)',NULL),
('Visakhapatnam','ECI + 5',NULL),
('Bangladesh','ECI + 5',NULL),
('IOC Haldia Refinery','ECI + 5',NULL),
('Dhamra Light.','ECI + 5',NULL),
('Aegis Pipavav','WCI + 5',NULL),
('Tuticorin','WCI + 5',NULL),
('Kakinada Fertilizer Terminal','WCI + 5',NULL),
('Hazira','WCI + 5',NULL),
('New Mangalore','WCI + 5',NULL),
('New Manglore','WCI + 5',NULL),
('Kochi','WCI + 5',NULL),
('Kochi LNG Terminal','WCI + 5',NULL),
('Mangalore','WCI + 5',NULL),
('LKCMB','WCI + 5',NULL),
('Colombo Anch','WCI + 5',NULL),
('Dahej','WCI + 5',NULL),
('Kandla','WCI + 5',NULL),
('Sikka','WCI + 5',NULL),
('BPCL Mumbai','WCI + 5',NULL),
('Mumbai','WCI + 5',NULL),
('West Coast India','WCI + 5',NULL),
('Mumbai Light.','WCI + 5',NULL),
('Mundra','WCI + 5',NULL),
('Villa Male tanks farm','Galle +2',NULL),
('LAUGFS Colombo','Galle +2',NULL),
('LAUGFS Hambantota','Galle +2',NULL),
('Male Anchorage','Galle +2',NULL),
('Male','Galle +2',NULL),
('Galle','Galle +2',NULL),
('Trincomalee Light.','Galle +2',NULL),
('Indian Ocean','Galle +2',NULL),
('India','Galle +2',NULL),
('Colombo','Galle +2',NULL),
('Sri Lanka','Galle +2',NULL),
('Manila','Philippines + 3',NULL),
('Sual','Philippines + 3',NULL),
('Philippines','Philippines + 3',NULL),
('Port Dickson Refinery','Philippines + 3',NULL),
('Liquigaz Sariaya Terminal','Philippines + 3',NULL),
('Batangas','Philippines + 3',NULL),
('Petron Mandaue Depot','Philippines + 3',NULL),
('Petron Bataan Refinery','Philippines + 3',NULL),
('Davao','Philippines + 3',NULL),
('Subic Bay','Philippines + 3',NULL),
('Liquigaz Sariaya','Philippines + 3',NULL),
('Luzon','Philippines + 3',NULL),
('Bataan','Philippines + 3',NULL),
('Hai Phong','Vietnam + 3',NULL),
('PV Vung Tau','Vietnam + 3',NULL),
('Vung Tau','Vietnam + 3',NULL),
('Philphos Fertilizer Plant','Vietnam + 3',NULL),
('PetroVietnam Vung Tau Oil Terminal','Vietnam + 3',NULL),
('Vietnam','Vietnam + 3',NULL),
('Ho Chi Minh','Vietnam + 3',NULL),
('Haiphong','Vietnam + 3',NULL),
('Thai Binh','Vietnam + 3',NULL),
('Map Ta Phut Terminal','Thailand +3',NULL),
('Sriracha LPG','Thailand +3',NULL),
('Sriracha LPG Terminal','Thailand +3',NULL),
('Arun','Indo + 4',NULL),
('Pupuk Ammonia','Indo + 4',NULL),
('Merak','Indo + 4',NULL),
('South-East Asia','Indo + 4',NULL),
('Teluk Semangka Terminal','Indo + 4',NULL),
('Kalbut','Indo + 4 (STS)',NULL),
('Bontang LPG','Indo + 4',NULL),
('Pertamina Bintan BBM','Indo + 4',NULL),
('Pertamina TBBM Tanjung Uban Import Terminal','Indo + 4',NULL),
('Indonesia','Indo + 4',NULL),
('Pertamina Panjang Bandar Lampung','Indo + 4',NULL),
('Teluk Kabung Terminal','Indo + 4',NULL),
('Teluk Semangka','Indo + 4',NULL),
('Oiltanking Merak','Indo + 4',NULL),
('Oiltank. Merak','Indo + 4',NULL),
('Batam Port','Indo + 4',NULL),
('Balikpapan','Indo + 4 (STS)',NULL),
('Anyer Terminal','Indo + 4',NULL),
('Teluk Kabung','Indo + 4',NULL),
('Pertamina Tanjung Sekong','Indo + 4',NULL),
('Kalbut Situbondo','Indo + 4 (STS)',NULL),
('Anyer','Indo + 4',NULL),
('Tanjung Priok','Indo + 4',NULL),
('Banggai','Indo + 4',NULL),
('Kalimantan','Indo + 4',NULL),
('Rayong','Thailand + 3',NULL),
('Thailand','Thailand + 3',NULL),
('Ko Sichang','Thailand + 3',NULL),
('Westernport','open \"Indo\" + 7',NULL),
('Botany','Australia + 2',NULL),
('Ichthys','Australia',NULL),
('Bonython','Australia',NULL),
('Gladstone','Australia',NULL),
('Bayu Undan FPSO','Australia',NULL),
('Dampier','Australia',NULL),
('Australia','Australia',NULL),
('Kwinana Ammonia','Australia',NULL),
('Channel Island LPG','Australia',NULL),
('Prelude FLNG','+5 days open Indo',NULL),
('Prelude','+5 days open Indo',NULL),
('North West Shelf LPG','Australia',NULL),
('BP Pinkenba','Aus discharge',NULL),
('Darwin','Put open \"Indo\" first',NULL),
('Repsol Tarragona Butano','Eu +8',NULL),
('Tarragona','Eu + 4',NULL),
('Stenungsund Terminal','Eu + 4',NULL),
('Fortuneswell','Eu + 4',NULL),
('Switzerland','Eu + 4',NULL),
('Kemaman','Eu + 4',NULL),
('Zeebrugge','Eu + 4',NULL),
('Terneuzen','Eu + 4',NULL),
('Ravenna','Eu + 4',NULL),
('Naples Refinery','Eu + 4',NULL),
('BE ANR H','Eu + 4',NULL),
('Rotterdam','Eu + 4',NULL),
('Skagen','Eu + 4',NULL),
('Netherlands','Eu + 4',NULL),
('Lavera 2','Eu + 4',NULL),
('Poland','Eu + 4',NULL),
('Vopak Vlissingen','Eu + 4',NULL),
('United Kingdom','Eu + 4',NULL),
('Port of Spain','Eu + 4',NULL),
('Zeebrugge LPG Terminal','Eu + 4',NULL),
('Borealis Porvoo','Eu + 4',NULL),
('English Channel','Eu + 4',NULL),
('Repsol Butano','Eu + 4',NULL),
('Repsol Cartagena Refinery','Eu + 4',NULL),
('Sines Terminal de Graneis Liquidos','Eu + 4',NULL),
('Fos','Eu + 4',NULL),
('Europe','Eu + 4',NULL),
('Donges','Eu + 4',NULL),
('Marseille','Eu + 4',NULL),
('Horizon Tangier Terminal','Eu + 4',NULL),
('Ceuta','Eu + 4',NULL),
('Le Havre','Eu + 4',NULL),
('BASF Antwerpen','Eu + 4',NULL),
('North West Europe Zone','Eu + 4',NULL),
('Teesside','Eu + 4',NULL),
('Ghent','Eu + 4',NULL),
('Gijon LPG','Eu + 4',NULL),
('Spain','Eu + 4',NULL),
('Portugal','Eu + 4',NULL),
('Le Havre Norgal','Eu + 4',NULL),
('Karlshamn','Eu + 4',NULL),
('Canvey Island','Eu + 4',NULL),
('Stenungsund','Eu + 4',NULL),
('Gothenburg','Eu + 4',NULL),
('BASF Antwerp','Eu + 4',NULL),
('Gijon LPG Terminal','Eu + 4',NULL),
('ETT Rotterdam','Eu + 4',NULL),
('Sines','Eu + 5',NULL),
('Denmark','Eu + 4',NULL),
('ARA','Eu + 4',NULL),
('Lisbon','Eu + 4',NULL),
('Vlissingen','Eu + 4',NULL),
('Porvoo LPG','Eu + 4',NULL),
('Immingham Gas','Eu + 4',NULL),
('Brest','Eu + 4',NULL),
('Fort de France Refinery','Eu + 4',NULL),
('Dunkirk','Eu + 4',NULL),
('Versalis Dunkirk Cracker','Eu + 4',NULL),
('Skagen Anchorage','Eu + 4',NULL),
('Immingham','Eu + 4',NULL),
('US MAH - NL VLI','Eu + 4',NULL),
('Brindisi','Eu + 4',NULL),
('Karsto','Eu + 4',NULL),
('Cartagena','Eu + 4',NULL),
('Karsto Processing Plant','Eu + 4',NULL),
('Dow Terneuzen','Eu + 4',NULL),
('Antwerp','Eu + 4',NULL),
('Brunsbuttel','Eu + 4',NULL),
('Oiltank. Amsterdam','Turkey + 5',NULL),
('Snohvit','Eu + 4',NULL),
('BMF Burgas','Turkey + 5',NULL),
('Burgas','Turkey + 5',NULL),
('Yara Sluiskil','Turkey + 5',NULL),
('Vopak Terminal Vlissingen','Turkey + 5',NULL),
('Swinoujscie Area','Turkey + 5',NULL),
('Bosphorus Strait','Turkey + 5',NULL),
('Augusta','Turkey + 5',NULL),
('Vassiliko','Turkey + 5',NULL),
('Livorno','Turkey + 5',NULL),
('Guzeliali Shipyard','Dry dock',NULL),
('Italy','Turkey + 5',NULL),
('Romano','Turkey + 5',NULL),
('Canakkale','Turkey + 5',NULL),
('Aygaz Izmit','Turkey + 5',NULL),
('Nemrut','Turkey + 5',NULL),
('Ceyhan','Turkey + 5',NULL),
('Turkey','Turkey + 5',NULL),
('Aliaga','Turkey + 5',NULL),
('Tuzla Shipyard','Dry dock',NULL),
('Equinor Mongstad Refinery','Greece (Turkey)',NULL),
('Piraeus','Greece (Turkey)',NULL),
('Aygaz-Ipragaz Terminal','Flushing',NULL),
('Nemrut LPG','Flushing',NULL),
('Alania','Gibraltar',NULL),
('Greece','Gibraltar',NULL),
('Gibraltar Dockyard','Gibraltar',NULL),
('Jorf Lasfar','Gibraltar',NULL),
('Flushing Anchorage 2','East Med',NULL),
('Falmouth','East Med',NULL),
('Vopak Terminal Vlissngen','East Med',NULL),
('Northern Europe','East Med',NULL),
('Gibraltar','East Med',NULL),
('Tangier','East Med',NULL),
('Tunisia','East Med',NULL),
('Valletta','East Med',NULL),
('Sarroch Refinery','East Med',NULL),
('Algeciras','East Med (Malta)',NULL),
('Gibraltar-San Roque Refinery','East Med (Cypress)',NULL),
('Malta','East Med (Greece)',NULL),
('Med SEA','East Med (Greece)',NULL),
('Limassol Light.','Mohammedia',NULL),
('Malta Light.','Mohammedia',NULL),
('Kalamata','Mohammedia',NULL),
('Kalamata Light.','Mohammedia',NULL),
('Morocco','Mohammedia',NULL),
('Tenerife','Mohammedia + 1',NULL),
('MOH Corinth Refinery','Mohammedia',NULL),
('Birzebbugia','Paldisky -> South/East China (Ust Luga, Estonia; likely SIBUR)',NULL),
('ZOUK','Paldisky -> South/East China (Ust Luga, Estonia; likely SIBUR)',NULL),
('AS Alexela Terminal','Paldisky -> South/East China (Ust Luga, Estonia; likely SIBUR)',NULL),
('Hualpen Gas','Chile',NULL),
('Mejillones','Chile',NULL),
('Quintero Lipigas','Chile',NULL),
('Quintero','Chile',NULL),
('Quintero Gasmar','Chile',NULL),
('Hualpen Gas Terminal','Mexico',NULL),
('Pajaritos','Mexico',NULL),
('Bay of Campeche','Mexico',NULL),
('Puerto Quetzal','Mexico',NULL),
('Mexico','Suape',NULL),
('Gulf of Mexico','Santos',NULL),
('Omoa LPG','Suape',NULL),
('Tuxpan','Suape',NULL),
('Tuxpan Termigas','Suape',NULL),
('Lazaro Cardenas LPG Terminal','Santos',NULL),
('Ensenada','Suape',NULL),
('Manzanillo','Monteverde (Ecuador)',NULL),
('Callao','Monteverde',NULL),
('Suape','Suape + 4',NULL),
('Santos','Santos',NULL),
('Rio Grande LPG','Suape + 4',NULL),
('Rio Grande LPG Terminal','Suape + 4',NULL),
('Rio de Janeiro LPG Terminal','Suape + 4',NULL),
('Brazil','Suape + 4',NULL),
('Monteverde','Monteverde (Ecuador)',NULL),
('Chorrillo','Monteverde (Ecuador)',NULL),
('Ecuador','Monteverde (Ecuador)',NULL),
('Crown Point','Suape + 4',NULL),
('BR SUA','Suape + 4',NULL),
('Bahia Blanca','Suape + 4',NULL),
('Santo Tomas de Castilla','Santos',NULL),
('La Teja Refinery','Santos + 2',NULL),
('RIPET','+14 days to Far East',NULL),
('Alemoa','Santos + 2',NULL),
('Port Bonython','Port Bonython',NULL),
('Manzanillo (Mexico)','Mexico',NULL),
('US POB','USG',NULL),
('PA BLB','Balboa',NULL),
('PA CTB','Balboa',NULL),
('PACTB','Balboa',NULL),
('IN ENR','WCI',NULL),
('IN HAL','WCI',NULL),
('JPCHB','Japan',NULL),
('JP CHB','Japan',NULL),
('MUPLU','Port Louis ballast',NULL),
('SG SIN','Singapore',NULL),
('US FPO','USG',NULL),
('US HOUNG','USG',NULL),
('KFK UAE','AG',NULL),
('KFK','AG',NULL),
('ID TSE','Indo + 4',NULL),
('KRUSN','Korea + 4',NULL),
('AE FUJ OPL','AG',NULL),
('Hyatt','Philippines + 3',NULL),
('Haldia Terminal','ECI + 5',NULL),
('Targa','USG',NULL),
('Jovo','East China + 4',NULL),
('Dushan Terminal','South China + 4',NULL),
('Satellite Energy Pinghu','East China + 4',NULL),
('Enterprise Neches River','USG',NULL),
('Kawasaki - Gyxis','Japan + 6',NULL),
('Aygaz-Ipragaz Dortyol','Dortyol',NULL),
('Lavera 1','Eu + 4',NULL),
('Asaluyeh','AG',NULL),
('Porbandar','WCI',NULL),
('GPS Klang Terminal','Malaysia + 2',NULL),
('Ningbo Hireal','East China + 4',NULL),
('Kawasaki - JGEC','Japan + 6',NULL),
('Ulsan LPG','Korea + 4',NULL),
('US FRP','USG',NULL),
('USGLS','USG',NULL),
('Morgan\'s Point','USG',NULL),
('JP KSM O','Japan',NULL),
('PBLB','Japan',NULL),
('PA-BLB','Japan',NULL),
('CN ZUH','South China',NULL),
('CRISTOBAL PANAMA','USG',NULL),
('USHOU>CNNBO','loads WAF',NULL),
('ZAPLZ','Richards Bay',NULL),
('BATANENG','Philippines',NULL),
('JG Summit Petchem Batangas','Philippines',NULL),
('HOU ENTERPRISE','loads USG',NULL),
('USFDT D6 HRS','loads USG',NULL),
('Negishi','East China',NULL),
('PA CTB >> JP NGO','loads USG',NULL),
('JPSDU','loads AG',NULL),
('CNTAX','loads Prince Rupert',NULL),
('MT MLA','loads WAF',NULL),
('PORT LOUIS MAURIY5','loads AG',NULL),
('EG PSE COVE','loads WAF',NULL),
('IN DMQNE SUR MER','Caribs',NULL),
('EG PSD','Greece',NULL),
('PABLB DRS','Balboa',NULL),
('TWKHH','Japan',NULL),
('CNZOS','East China',NULL),
('Xiaoqian Shipyard','East China',NULL),
('CNLYG','Honolulu',NULL),
('USPAU','loads USG',NULL),
('Repauno Terminal','loads USG',NULL),
('E8IJING LD','East China',NULL),
('INDIASHIP ALLINDIAN','Oman',NULL),
('VN FOR ORDER','Brazil',NULL),
('CNNBG','Open AG',NULL),
('PA BLALIZABETH','Balboa',NULL),
('USHOU D6 HRS','Mexico',NULL),
('INENR','Indo',NULL),
('HOUSTON,US','Open USG',NULL),
('GI GIB','Greece',NULL),
('LK GAM','Brazil',NULL),
('CN JAX','South Korea',NULL),
('US NDX >> PA CRT','Cayman',NULL),
('JP KAR>PA BLB','West Mexico',NULL),
('ESTER','loads AG',NULL),
('USCRP>PACTB','loads USG',NULL),
('PA CTBITGIT','Balboa',NULL),
('USHOU>JPCHB','Brazil',NULL),
('CN NBG','loads USG',NULL),
('AO DKX','loads WAF',NULL),
('PA BLB FOR ORDERS','East China',NULL),
('SG SIMNG','loads WAF',NULL),
('BE ANR','East Med',NULL),
('FOR OQNG','Brazil',NULL),
('SGSIN=NG','loads USG',NULL),
('DONGGUAN','loads USG',NULL),
('KRYOS >PABLB','Mexico',NULL),
('Sakai Refinery','West Mexico',NULL),
('USGLS DE 33 HRS','Cape ballast',NULL),
('USBLI > KRUSN','Korea',NULL),
('US HOU>NL TNZ','Terneuzen',NULL),
('KR YOS>PA BLB','West Mexico',NULL),
('KRPTK >PABLB','Open USG',NULL),
('PACTB - KRUSN','loads USG',NULL),
('MU PLU=>>ZA PLZ','East Med',NULL),
('US HOT','Malaysia ballast',NULL),
('KRYOS-PNBLB','Open AG',NULL),
('PORT ELIZABETH OP','Richards Bay',NULL),
('KRYOS','South Korea',NULL),
('Kawasaki - Eneos Globe','Australia',NULL),
('LKGAL','Malaysia ballast',NULL),
('JP YKK','Japan',NULL),
('PABAL','Japan',NULL),
('Long Son Petrochems','Brazil',NULL),
('BEANR','loads AG',NULL),
('ZA CPT','Cape ballast',NULL),
('PABLB=NG','Open AG',NULL),
('TR DYL','Turkey',NULL),
('PORT QI','Suez',NULL),
('SG SIN>US HOU','Cape ballast',NULL),
('PA BL','Balboa',NULL),
('TH SRI','loads AG',NULL),
('USFPO>>PACTB','loads USG',NULL),
('PAPCN','Open AG',NULL),
('SGSIN-AEFJR','Oman',NULL),
('US HNL','Honolulu',NULL),
('USHOU ORES','Bahamas',NULL),
('JP ANE OFF/T5','Japan',NULL),
('Idemitsu Chiba Kosan Refinery','Japan',NULL),
('NL TNXORE WATERS','loads AG',NULL),
('IDKSO','East China',NULL),
('BE ANR KA','Terneuzen',NULL),
('Antwerp Gas','Terneuzen',NULL),
('SG PWBG A','Brazil',NULL),
('HOU USA','Open AG',NULL),
('SGSIN>USFPO','Brazil',NULL),
('HOUSTON #Z8','Open USG',NULL),
('FREEPORT/USA','Australia',NULL),
('FREEPORT,USA','Open USG',NULL),
('KR YOS','South Korea',NULL),
('USA HOUSTON','Malaysia ballast',NULL),
('USTX','Malaysia ballast',NULL),
('Grand Resource Dongguan','Malaysia ballast',NULL),
('SGSIN-USHOU','Port Louis ballast',NULL),
('Salalah LPG','Malaysia laden',NULL),
('PABLB=>JPMIZ','Japan',NULL),
('JPKWS>PABLB','Open AG',NULL),
('KALBUT ID','Malaysia ballast',NULL),
('ESCEU>USHOU','WAF',NULL),
('Bethioua','WAF',NULL),
('CROSTOBAL PA','Caribs',NULL),
('PA BLANG','Balboa',NULL),
('DO SPM>US HOU','loads USG',NULL),
('TR IST','Turkey',NULL),
('Milangaz İzmit','Turkey',NULL),
('CN LYEI','Port Louis ballast',NULL),
('Sinochem Lianyungang','Port Louis ballast',NULL),
('ARBHI','Malaysia ballast',NULL)
ON DUPLICATE KEY UPDATE area=VALUES(area), region=VALUES(region);

CREATE TABLE IF NOT EXISTS port_aliases (id INT AUTO_INCREMENT PRIMARY KEY, alias_name VARCHAR(255) UNIQUE, canonical_name VARCHAR(255));
INSERT INTO port_aliases (alias_name, canonical_name) VALUES
('New Mangalore','WCI'),
('Ennore','ECI'),
('Haldia','ECI'),
('Chittagong','Bangladesh'),
('no Cape ballast - since the ship won\'t deviate back to AG','Cape laden'),
('no Port Louis ballast - since the ship won\'t deviate back to AG','Port Louis laden'),
('Teluk Semangka','Indo'),
('MTP','Thailand'),
('Vungtao','Vietnam'),
('Bataan','Philippines'),
('Kaohsiung','Taiwan'),
('Mailiao','Taiwan'),
('ZJG is very close to 16 days','Ningbo'),
('Ningbo','China'),
('Dongguan','South China'),
('Ulsan','Korea'),
('Chiba','Japan'),
('Tianjin, Yantai (17 days)','North China'),
('Brisbane, Botany Bay','Australia'),
('Dortyol','Turkey'),
('Bonny','WAF'),
('Oman','Oman'),
('Yantai','North China'),
('Add it just in case','Taiwan'),
('Suez canal exit','Suez'),
('Vung Tau','Vietnam'),
('Botany','Botany'),
('Antwerp','Turkey'),
('Zanzibar','Tanzania'),
('Quintero','Chile'),
('Tuxpan','Mexico'),
('Tarragona (Spain)','Eu'),
('Stenungsung (Sweden)','Eu'),
('Rotterdam','Eu'),
('Skagen (Denmark)','Eu'),
('St Thomas','BVI'),
('(Morocco)','Mohammedia'),
('(Hualpen)','Quintero'),
('Malta','East Med'),
('Puerto Viejo de Azua','Ocoa Bay'),
('Las Palmas (Canary Islands)','Las Palmas (Canary Islands)'),
('La Libertad, Ecaudor','Monteverde'),
('Port Louis','Port Louis laden'),
('No Cape laden - since vessel haven\'t discharged','Cape ballast'),
('Freeport Bahamas','Bahamas'),
('Omoa','Mexico'),
('George Town','Cayman'),
('Yeosu','Korea'),
('Panjin','North China'),
('Arzew (Algeria)','Algeria'),
('Terneuzen','Terneuzen'),
('Tanjung Sekong','Indo'),
('Vungtau','Vietnam'),
('Dev Point','Galle'),
('Or Tangiers','Mohammedia'),
('Dortyol, Izmit','Turkey'),
('Teluk Semangka - Singapore - Bonny','Indo'),
('MTP,Rayong','Thailand'),
('Tianjin','North China'),
('Port Elizabeth','Cape ballast'),
('Yesil Terminal','Dortyol'),
('Westport','Malaysia ballast'),
('Kalbut','Indo'),
('New Mangolare','WCI'),
('Fujairah','AG'),
('Jizan','Suez'),
('Botany Bay','Australia'),
('Daxie Ningbo','East China'),
('Jiangsu Yangtzejiang Petrochemical','East China'),
('Taixing','East China'),
('Dongjiakou','North China'),
('Tianjin Lingang','North China'),
('Zhangjiagang','North China'),
('Fuzhou','South China'),
('Raoping','South China'),
('Qinzhou','Southwest China'),
('Guangxi Tiansheng','Southwest China'),
('Aomori','Japan'),
('Chita Fuels Terminal','Japan'),
('Cosmo Matsuyama','Japan'),
('Hekinan','Japan'),
('Idemitsu Chiba Kosan Refinery','Japan'),
('Imari','Japan'),
('Iwatani Sakai','Japan'),
('Karatsu','Japan'),
('Kashima JGE','Japan'),
('Kashima LPG','Japan'),
('Kawasaki - Eneos Globe','Japan'),
('Kawasaki - Gyxis','Japan'),
('Kawasaki - JGEC','Japan'),
('Marubeni Chiba','Japan'),
('Matsuura Kyushu','Japan'),
('Namikata','Japan'),
('Nanao','Japan'),
('Niigata','Japan'),
('Nippon Mizushima Refinery B','Japan'),
('Oita','Japan'),
('Oita Refinery','Japan'),
('Osaka','Japan'),
('Sakai Refinery','Japan'),
('Sakaide','Japan'),
('Sendai Refinery','Japan'),
('Showa Kobe','Japan'),
('Tokuyama LPG','Japan'),
('Yokkaichi Plant','Japan'),
('Incheon LPG','South Korea'),
('SK Gas Pyeongtaek','South Korea'),
('Singapore','Singapore laden'),
('Map Ta Phut','Thailand'),
('Mumbai','WCI'),
('Galle','Galle'),
('Open AG','Open AG'),
('Richards Bay','Richards Bay'),
('Suape','Brazil'),
('Porvoo','Eu'),
('Kalamata','Greece'),
('Ain Sukhna','Suez'),
('San Pedro?','Ocoa'),
('Ridley Island','loads Prince Rupert'),
('Ferndale','loads Prince Rupert'),
('Port Bonython','Bonython')
ON DUPLICATE KEY UPDATE canonical_name=VALUES(canonical_name);

CREATE TABLE IF NOT EXISTS destinations (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), `key` VARCHAR(255) UNIQUE, sort_order INT DEFAULT 0);
INSERT INTO destinations (name, `key`, sort_order) VALUES
(NULL,'AG',1),
(NULL,'USG_PANAMA',2),
(NULL,'USG_CAPE',3),
(NULL,'WAF',4),
(NULL,'BETHIOUA',5),
(NULL,'SINGAPORE',6),
(NULL,'WESTERNPORT',7),
(NULL,'DARWIN',8),
(NULL,'PRINCE_RUPERT',9),
(NULL,'BONYTHON',10),
(NULL,'YANBU',11)
ON DUPLICATE KEY UPDATE name=VALUES(name), sort_order=VALUES(sort_order);
